### ISSUE TITLE
Please check the url and the case when user pass in a single name

### ISSUE THREAD

**Issue by jiajianzhou** [block8437/gender.py#6]

**Comment by block8437** [comment]
Can you please clarify the issue?

**Comment by jiajianzhou** [comment]
like when I call getGenders('Peter'), the script will crash. And I found the example url at https://genderize.io is follow:
GET https://api.genderize.io/?name=peter

**Comment by block8437** [comment]
This was because of updates to the API. This was fixed with the last commit.
